#!/bin/bash
#SBATCH --job-name=<dtmkTGPT>
#SBATCH --mail-user=<wang.qing@ufl.edu>
#SBATCH --mail-type=FAIL,END
#SBATCH --output <my_job-%j.out>
#SBATCH --time=24:00:00
#SBATCH --partition=hpg2-compute
#SBATCH --cpus-per-task=8
#SBATCH --mem=40gb

python dataset_makingV2.py